name: Tests and formatting
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm run tsc
    - run: npm test
      env:
        CI: true
    - run: npm run check-format
